server:
  port: 5601
  servlet:
    context-path: /ui

security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: ermdev
      clientSecret: secret
      accessTokenUri: http://localhost:5600/auth/oauth/token
      userAuthorizationUri: http://localhost:5600/auth/oauth/authorize
    resource:
      userInfoUri: http://localhost:5600/auth/hello/principal